/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoftFacilityRouteImport } from './routes/soft-facility'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PropreteRouteImport } from './routes/proprete'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AmoRouteImport } from './routes/amo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropreteIndexRouteImport } from './routes/proprete.index'
import { Route as SecteurSlugRouteImport } from './routes/secteur.$slug'
import { Route as PropreteSyndicsCoproprieteRouteImport } from './routes/proprete.syndics-copropriete'
import { Route as PropreteSlugRouteImport } from './routes/proprete.$slug'

const SoftFacilityRoute = SoftFacilityRouteImport.update({
  id: '/soft-facility',
  path: '/soft-facility',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PropreteRoute = PropreteRouteImport.update({
  id: '/proprete',
  path: '/proprete',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AmoRoute = AmoRouteImport.update({
  id: '/amo',
  path: '/amo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropreteIndexRoute = PropreteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropreteRoute,
} as any)
const SecteurSlugRoute = SecteurSlugRouteImport.update({
  id: '/secteur/$slug',
  path: '/secteur/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PropreteSyndicsCoproprieteRoute =
  PropreteSyndicsCoproprieteRouteImport.update({
    id: '/syndics-copropriete',
    path: '/syndics-copropriete',
    getParentRoute: () => PropreteRoute,
  } as any)
const PropreteSlugRoute = PropreteSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PropreteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amo': typeof AmoRoute
  '/contact': typeof ContactRoute
  '/proprete': typeof PropreteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soft-facility': typeof SoftFacilityRoute
  '/proprete/$slug': typeof PropreteSlugRoute
  '/proprete/syndics-copropriete': typeof PropreteSyndicsCoproprieteRoute
  '/secteur/$slug': typeof SecteurSlugRoute
  '/proprete/': typeof PropreteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amo': typeof AmoRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soft-facility': typeof SoftFacilityRoute
  '/proprete/$slug': typeof PropreteSlugRoute
  '/proprete/syndics-copropriete': typeof PropreteSyndicsCoproprieteRoute
  '/secteur/$slug': typeof SecteurSlugRoute
  '/proprete': typeof PropreteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amo': typeof AmoRoute
  '/contact': typeof ContactRoute
  '/proprete': typeof PropreteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soft-facility': typeof SoftFacilityRoute
  '/proprete/$slug': typeof PropreteSlugRoute
  '/proprete/syndics-copropriete': typeof PropreteSyndicsCoproprieteRoute
  '/secteur/$slug': typeof SecteurSlugRoute
  '/proprete/': typeof PropreteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amo'
    | '/contact'
    | '/proprete'
    | '/sitemap.xml'
    | '/soft-facility'
    | '/proprete/$slug'
    | '/proprete/syndics-copropriete'
    | '/secteur/$slug'
    | '/proprete/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amo'
    | '/contact'
    | '/sitemap.xml'
    | '/soft-facility'
    | '/proprete/$slug'
    | '/proprete/syndics-copropriete'
    | '/secteur/$slug'
    | '/proprete'
  id:
    | '__root__'
    | '/'
    | '/amo'
    | '/contact'
    | '/proprete'
    | '/sitemap.xml'
    | '/soft-facility'
    | '/proprete/$slug'
    | '/proprete/syndics-copropriete'
    | '/secteur/$slug'
    | '/proprete/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmoRoute: typeof AmoRoute
  ContactRoute: typeof ContactRoute
  PropreteRoute: typeof PropreteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoftFacilityRoute: typeof SoftFacilityRoute
  SecteurSlugRoute: typeof SecteurSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soft-facility': {
      id: '/soft-facility'
      path: '/soft-facility'
      fullPath: '/soft-facility'
      preLoaderRoute: typeof SoftFacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprete': {
      id: '/proprete'
      path: '/proprete'
      fullPath: '/proprete'
      preLoaderRoute: typeof PropreteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amo': {
      id: '/amo'
      path: '/amo'
      fullPath: '/amo'
      preLoaderRoute: typeof AmoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprete/': {
      id: '/proprete/'
      path: '/'
      fullPath: '/proprete/'
      preLoaderRoute: typeof PropreteIndexRouteImport
      parentRoute: typeof PropreteRoute
    }
    '/secteur/$slug': {
      id: '/secteur/$slug'
      path: '/secteur/$slug'
      fullPath: '/secteur/$slug'
      preLoaderRoute: typeof SecteurSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprete/syndics-copropriete': {
      id: '/proprete/syndics-copropriete'
      path: '/syndics-copropriete'
      fullPath: '/proprete/syndics-copropriete'
      preLoaderRoute: typeof PropreteSyndicsCoproprieteRouteImport
      parentRoute: typeof PropreteRoute
    }
    '/proprete/$slug': {
      id: '/proprete/$slug'
      path: '/$slug'
      fullPath: '/proprete/$slug'
      preLoaderRoute: typeof PropreteSlugRouteImport
      parentRoute: typeof PropreteRoute
    }
  }
}

interface PropreteRouteChildren {
  PropreteSlugRoute: typeof PropreteSlugRoute
  PropreteSyndicsCoproprieteRoute: typeof PropreteSyndicsCoproprieteRoute
  PropreteIndexRoute: typeof PropreteIndexRoute
}

const PropreteRouteChildren: PropreteRouteChildren = {
  PropreteSlugRoute: PropreteSlugRoute,
  PropreteSyndicsCoproprieteRoute: PropreteSyndicsCoproprieteRoute,
  PropreteIndexRoute: PropreteIndexRoute,
}

const PropreteRouteWithChildren = PropreteRoute._addFileChildren(
  PropreteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmoRoute: AmoRoute,
  ContactRoute: ContactRoute,
  PropreteRoute: PropreteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoftFacilityRoute: SoftFacilityRoute,
  SecteurSlugRoute: SecteurSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
