/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoftFacilityRouteImport } from './routes/soft-facility'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PropreteRouteImport } from './routes/proprete'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AmoRouteImport } from './routes/amo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropreteIndexRouteImport } from './routes/proprete.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SoftFacilitySlugRouteImport } from './routes/soft-facility_.$slug'
import { Route as SecteurSlugRouteImport } from './routes/secteur.$slug'
import { Route as PropreteSyndicsCoproprieteRouteImport } from './routes/proprete.syndics-copropriete'
import { Route as PropreteSurfaceVenteErpRouteImport } from './routes/proprete.surface-vente-erp'
import { Route as PropreteProfessionnelsSanteRouteImport } from './routes/proprete.professionnels-sante'
import { Route as PropretePharmaceutiqueRouteImport } from './routes/proprete.pharmaceutique'
import { Route as PropreteSlugRouteImport } from './routes/proprete.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SoftFacilityRoute = SoftFacilityRouteImport.update({
  id: '/soft-facility',
  path: '/soft-facility',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PropreteRoute = PropreteRouteImport.update({
  id: '/proprete',
  path: '/proprete',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AmoRoute = AmoRouteImport.update({
  id: '/amo',
  path: '/amo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropreteIndexRoute = PropreteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropreteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const SoftFacilitySlugRoute = SoftFacilitySlugRouteImport.update({
  id: '/soft-facility_/$slug',
  path: '/soft-facility/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SecteurSlugRoute = SecteurSlugRouteImport.update({
  id: '/secteur/$slug',
  path: '/secteur/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PropreteSyndicsCoproprieteRoute =
  PropreteSyndicsCoproprieteRouteImport.update({
    id: '/syndics-copropriete',
    path: '/syndics-copropriete',
    getParentRoute: () => PropreteRoute,
  } as any)
const PropreteSurfaceVenteErpRoute = PropreteSurfaceVenteErpRouteImport.update({
  id: '/surface-vente-erp',
  path: '/surface-vente-erp',
  getParentRoute: () => PropreteRoute,
} as any)
const PropreteProfessionnelsSanteRoute =
  PropreteProfessionnelsSanteRouteImport.update({
    id: '/professionnels-sante',
    path: '/professionnels-sante',
    getParentRoute: () => PropreteRoute,
  } as any)
const PropretePharmaceutiqueRoute = PropretePharmaceutiqueRouteImport.update({
  id: '/pharmaceutique',
  path: '/pharmaceutique',
  getParentRoute: () => PropreteRoute,
} as any)
const PropreteSlugRoute = PropreteSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PropreteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amo': typeof AmoRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/proprete': typeof PropreteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soft-facility': typeof SoftFacilityRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/proprete/$slug': typeof PropreteSlugRoute
  '/proprete/pharmaceutique': typeof PropretePharmaceutiqueRoute
  '/proprete/professionnels-sante': typeof PropreteProfessionnelsSanteRoute
  '/proprete/surface-vente-erp': typeof PropreteSurfaceVenteErpRoute
  '/proprete/syndics-copropriete': typeof PropreteSyndicsCoproprieteRoute
  '/secteur/$slug': typeof SecteurSlugRoute
  '/soft-facility/$slug': typeof SoftFacilitySlugRoute
  '/blog/': typeof BlogIndexRoute
  '/proprete/': typeof PropreteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amo': typeof AmoRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soft-facility': typeof SoftFacilityRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/proprete/$slug': typeof PropreteSlugRoute
  '/proprete/pharmaceutique': typeof PropretePharmaceutiqueRoute
  '/proprete/professionnels-sante': typeof PropreteProfessionnelsSanteRoute
  '/proprete/surface-vente-erp': typeof PropreteSurfaceVenteErpRoute
  '/proprete/syndics-copropriete': typeof PropreteSyndicsCoproprieteRoute
  '/secteur/$slug': typeof SecteurSlugRoute
  '/soft-facility/$slug': typeof SoftFacilitySlugRoute
  '/blog': typeof BlogIndexRoute
  '/proprete': typeof PropreteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amo': typeof AmoRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/proprete': typeof PropreteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soft-facility': typeof SoftFacilityRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/proprete/$slug': typeof PropreteSlugRoute
  '/proprete/pharmaceutique': typeof PropretePharmaceutiqueRoute
  '/proprete/professionnels-sante': typeof PropreteProfessionnelsSanteRoute
  '/proprete/surface-vente-erp': typeof PropreteSurfaceVenteErpRoute
  '/proprete/syndics-copropriete': typeof PropreteSyndicsCoproprieteRoute
  '/secteur/$slug': typeof SecteurSlugRoute
  '/soft-facility_/$slug': typeof SoftFacilitySlugRoute
  '/blog/': typeof BlogIndexRoute
  '/proprete/': typeof PropreteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amo'
    | '/blog'
    | '/contact'
    | '/mentions-legales'
    | '/proprete'
    | '/sitemap.xml'
    | '/soft-facility'
    | '/blog/$slug'
    | '/proprete/$slug'
    | '/proprete/pharmaceutique'
    | '/proprete/professionnels-sante'
    | '/proprete/surface-vente-erp'
    | '/proprete/syndics-copropriete'
    | '/secteur/$slug'
    | '/soft-facility/$slug'
    | '/blog/'
    | '/proprete/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amo'
    | '/contact'
    | '/mentions-legales'
    | '/sitemap.xml'
    | '/soft-facility'
    | '/blog/$slug'
    | '/proprete/$slug'
    | '/proprete/pharmaceutique'
    | '/proprete/professionnels-sante'
    | '/proprete/surface-vente-erp'
    | '/proprete/syndics-copropriete'
    | '/secteur/$slug'
    | '/soft-facility/$slug'
    | '/blog'
    | '/proprete'
  id:
    | '__root__'
    | '/'
    | '/amo'
    | '/blog'
    | '/contact'
    | '/mentions-legales'
    | '/proprete'
    | '/sitemap.xml'
    | '/soft-facility'
    | '/blog/$slug'
    | '/proprete/$slug'
    | '/proprete/pharmaceutique'
    | '/proprete/professionnels-sante'
    | '/proprete/surface-vente-erp'
    | '/proprete/syndics-copropriete'
    | '/secteur/$slug'
    | '/soft-facility_/$slug'
    | '/blog/'
    | '/proprete/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmoRoute: typeof AmoRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PropreteRoute: typeof PropreteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoftFacilityRoute: typeof SoftFacilityRoute
  SecteurSlugRoute: typeof SecteurSlugRoute
  SoftFacilitySlugRoute: typeof SoftFacilitySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soft-facility': {
      id: '/soft-facility'
      path: '/soft-facility'
      fullPath: '/soft-facility'
      preLoaderRoute: typeof SoftFacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprete': {
      id: '/proprete'
      path: '/proprete'
      fullPath: '/proprete'
      preLoaderRoute: typeof PropreteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amo': {
      id: '/amo'
      path: '/amo'
      fullPath: '/amo'
      preLoaderRoute: typeof AmoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprete/': {
      id: '/proprete/'
      path: '/'
      fullPath: '/proprete/'
      preLoaderRoute: typeof PropreteIndexRouteImport
      parentRoute: typeof PropreteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/soft-facility_/$slug': {
      id: '/soft-facility_/$slug'
      path: '/soft-facility/$slug'
      fullPath: '/soft-facility/$slug'
      preLoaderRoute: typeof SoftFacilitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secteur/$slug': {
      id: '/secteur/$slug'
      path: '/secteur/$slug'
      fullPath: '/secteur/$slug'
      preLoaderRoute: typeof SecteurSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprete/syndics-copropriete': {
      id: '/proprete/syndics-copropriete'
      path: '/syndics-copropriete'
      fullPath: '/proprete/syndics-copropriete'
      preLoaderRoute: typeof PropreteSyndicsCoproprieteRouteImport
      parentRoute: typeof PropreteRoute
    }
    '/proprete/surface-vente-erp': {
      id: '/proprete/surface-vente-erp'
      path: '/surface-vente-erp'
      fullPath: '/proprete/surface-vente-erp'
      preLoaderRoute: typeof PropreteSurfaceVenteErpRouteImport
      parentRoute: typeof PropreteRoute
    }
    '/proprete/professionnels-sante': {
      id: '/proprete/professionnels-sante'
      path: '/professionnels-sante'
      fullPath: '/proprete/professionnels-sante'
      preLoaderRoute: typeof PropreteProfessionnelsSanteRouteImport
      parentRoute: typeof PropreteRoute
    }
    '/proprete/pharmaceutique': {
      id: '/proprete/pharmaceutique'
      path: '/pharmaceutique'
      fullPath: '/proprete/pharmaceutique'
      preLoaderRoute: typeof PropretePharmaceutiqueRouteImport
      parentRoute: typeof PropreteRoute
    }
    '/proprete/$slug': {
      id: '/proprete/$slug'
      path: '/$slug'
      fullPath: '/proprete/$slug'
      preLoaderRoute: typeof PropreteSlugRouteImport
      parentRoute: typeof PropreteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PropreteRouteChildren {
  PropreteSlugRoute: typeof PropreteSlugRoute
  PropretePharmaceutiqueRoute: typeof PropretePharmaceutiqueRoute
  PropreteProfessionnelsSanteRoute: typeof PropreteProfessionnelsSanteRoute
  PropreteSurfaceVenteErpRoute: typeof PropreteSurfaceVenteErpRoute
  PropreteSyndicsCoproprieteRoute: typeof PropreteSyndicsCoproprieteRoute
  PropreteIndexRoute: typeof PropreteIndexRoute
}

const PropreteRouteChildren: PropreteRouteChildren = {
  PropreteSlugRoute: PropreteSlugRoute,
  PropretePharmaceutiqueRoute: PropretePharmaceutiqueRoute,
  PropreteProfessionnelsSanteRoute: PropreteProfessionnelsSanteRoute,
  PropreteSurfaceVenteErpRoute: PropreteSurfaceVenteErpRoute,
  PropreteSyndicsCoproprieteRoute: PropreteSyndicsCoproprieteRoute,
  PropreteIndexRoute: PropreteIndexRoute,
}

const PropreteRouteWithChildren = PropreteRoute._addFileChildren(
  PropreteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmoRoute: AmoRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PropreteRoute: PropreteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoftFacilityRoute: SoftFacilityRoute,
  SecteurSlugRoute: SecteurSlugRoute,
  SoftFacilitySlugRoute: SoftFacilitySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
